### ISSUE TITLE
Suggestion: Allow stained glass to be undyed, and/or be able to be used in crafting other colours of glass

### ISSUE THREAD

**Issue by HalfOfAKebab** [Joshimuz/VanillaWithFlake#8]
In vanilla, if you overproduce a certain colour of glass you might as well just burn it, because you can't undye it or dye it a new colour.

**Comment by rybak** [comment]
Would re-smelting coloured glass in the furnace make sense?

**Comment by rybak** [comment]
Yesterday, while playing on the 1.18 server, when we crafted one stack too many of Blue Stained Glass Panes, I had the exact same thought as I did in March.

**Comment by Joshimuz** [comment]
Yeah resmelting it to remove colour is a good idea, annoying to implement though because all the glasses are different items so I'd need to make a custom recipe for every colour of glass block and glass pane, but doable!

EDIT: Actually I might be able to make use of the tags system for this. Make a new tag for both coloured glass blocks and coloured glass panes, and make those tags smeltable into uncoloured versions
